# Use official Go image as base
FROM golang:1.25-alpine

# Set working directory inside container
WORKDIR /app

# Copy Go modules manifests
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build the Go binary
COPY user-service .

# Expose port (if your service listens on 8080)
EXPOSE 8080

# Run binary
CMD ["./user-service"]